name: Test Push Workflow
on: push
jobs:
   first-job:
     runs on: ubuntu-latest
     steps: 
        - name: Get code
          uses: actions/checkout
        - name: Print
          run: "done.."  